# Generated by Django 4.2.5 on 2023-09-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
